micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Pepsi!@#123'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update


