micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: jdbc:mysql://mysql:3306/pix?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "bruno"
    password: "12345"
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update


